name: YU-SEI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        working-directory: ./apps/yu-sei
        run: yarn build

      - name: Build libs
        run: |
          yarn workspace @ygo/crawler build
          yarn workspace @ygo/google-apis build
          yarn workspace @ygo/line build
          yarn workspace @ygo/mailer build
          yarn workspace @ygo/mongo-server build
          yarn workspace @ygo/schemas build
          yarn workspace @ygo/ruten-apis build

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Update known_hosts file
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts

      - name: Create .env file
        run: |
          echo "ADMIN=${{ secrets.ADMIN }}" >> .env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
          echo "DB=${{ secrets.DB }}" >> .env
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "EPASSWORD=${{ secrets.EPASSWORD }}" >> .env
          echo "LINENOTIFY=${{ secrets.LINENOTIFY }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "REDIRECT_URI=${{ secrets.REDIRECT_URI }}" >> .env
          echo "REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }}" >> .env

      - name: Clear cron_job folder except log
        run: |
          ssh root@${{ secrets.HOSTNAME }} "find /root/cron_job -mindepth 1 ! -regex '^/root/cron_job/log\(/.*\)?' -delete"

      - name: Create target directories
        run: |
          ssh root@${{ secrets.HOSTNAME }} "mkdir -p /root/cron_job/libs/crawler/dist"
          ssh root@${{ secrets.HOSTNAME }} "mkdir -p /root/cron_job/libs/google-apis/dist"
          ssh root@${{ secrets.HOSTNAME }} "mkdir -p /root/cron_job/libs/line/dist"
          ssh root@${{ secrets.HOSTNAME }} "mkdir -p /root/cron_job/libs/mailer/dist"
          ssh root@${{ secrets.HOSTNAME }} "mkdir -p /root/cron_job/libs/mongo-server/dist"
          ssh root@${{ secrets.HOSTNAME }} "mkdir -p /root/cron_job/libs/schemas/dist"
          ssh root@${{ secrets.HOSTNAME }} "mkdir -p /root/cron_job/libs/ruten-apis/dist"

      - name: Transfer files
        run: |
          rsync -avz --delete ./apps/yu-sei/dist/ root@${{ secrets.HOSTNAME }}:/root/cron_job/dist
          rsync -avz --delete ./apps/yu-sei/package.json root@${{ secrets.HOSTNAME }}:/root/cron_job/package.json
          rsync -avz --delete ./node_modules/ root@${{ secrets.HOSTNAME }}:/root/cron_job/node_modules
          rsync -avz --delete ./libs/crawler/dist/ root@${{ secrets.HOSTNAME }}:/root/cron_job/libs/crawler/dist
          rsync -avz --delete ./libs/google-apis/dist/ root@${{ secrets.HOSTNAME }}:/root/cron_job/libs/google-apis/dist
          rsync -avz --delete ./libs/line/dist/ root@${{ secrets.HOSTNAME }}:/root/cron_job/libs/line/dist
          rsync -avz --delete ./libs/mailer/dist/ root@${{ secrets.HOSTNAME }}:/root/cron_job/libs/mailer/dist
          rsync -avz --delete ./libs/mongo-server/dist/ root@${{ secrets.HOSTNAME }}:/root/cron_job/libs/mongo-server/dist
          rsync -avz --delete ./libs/schemas/dist/ root@${{ secrets.HOSTNAME }}:/root/cron_job/libs/schemas/dist
          rsync -avz --delete ./libs/ruten-apis/dist/ root@${{ secrets.HOSTNAME }}:/root/cron_job/libs/ruten-apis/dist
          scp .env root@${{ secrets.HOSTNAME }}:/root/cron_job/
