name: YU-SEI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build all projects
        run: yarn workspaces run build

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Update known_hosts file
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.HOSTNAME }} >> ~/.ssh/known_hosts

      - name: Create .env file
        run: |
          echo "ADMIN=${{ secrets.ADMIN }}" >> .env
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
          echo "DB=${{ secrets.DB }}" >> .env
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "EPASSWORD=${{ secrets.EPASSWORD }}" >> .env
          echo "LINENOTIFY=${{ secrets.LINENOTIFY }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "REDIRECT_URI=${{ secrets.REDIRECT_URI }}" >> .env
          echo "REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }}" >> .env

      - name: Clear cron_job folder except log
        run: |
          ssh root@${{ secrets.HOSTNAME }} "find /root/cron_job -mindepth 1 ! -regex '^/root/cron_job/log\(/.*\)?' -delete"

      - name: Transfer files
        run: |
          rsync -avz ./apps/yu-sei/dist/ root@${{ secrets.HOSTNAME }}:/root/cron_job/dist
          rsync -avz ./apps/yu-sei/package.json root@${{ secrets.HOSTNAME }}:/root/cron_job/package.json
          rsync -avz ./node_modules/ root@${{ secrets.HOSTNAME }}:/root/cron_job/node_modules
          rsync -avz ./libs/ root@${{ secrets.HOSTNAME }}:/root/cron_job/libs
          scp .env root@${{ secrets.HOSTNAME }}:/root/cron_job/

      - name: Install dependencies on server
        run: |
          ssh root@${{ secrets.HOSTNAME }} "cd /root/cron_job && yarn install"
